.gitignore
src/components/layout/BottomBanner.tsx
src/components/layout/RoundedButton.ts
src/components/layout/index.ts

- Creazione di un componente ad alto livello per il banner a fondo pagina
- Creato una variante del bottone Rounded

feat: create banner components

---

gatsby-node.js

- Aggiunta if per creare le pagine solo quando il loro body non è null

feat:Create route only for article with body

---

src/components/layout/ProjectCard.ts
src/components/layout/index.ts
src/components/project/ProjectContent.tsx
src/components/project/ProjectImage.tsx
src/components/project/SingleProject.tsx
src/pages/about.tsx

- Creato componenti da usare per le card dei progetti
- Tutti i componenti dovranno poi essere spostati nella folder `feature` presente in projects
- Creare Hover 
- Definire Altezza dell'immagine una volta stabilito uno standard di caricamento delle immagini ( probabile 1080x1080 )

feat: new single Project component

---

gatsby-node.js
query.js
src/feature/footer/footerdata.ts
src/feature/navigation/hooks/useNavigationLink.ts
src/template/ProjectsCategory.tsx
src/template/ProjectsHome.tsx

Create lato server: 
- Route per Home Page dei progetti
- Routes delle singole pagine delle categorie di progetti

feat(projects): create category & home

---

package.json
src/feature/projects/components/ArticleBody.tsx
yarn.lock

- installed react-syntax-highlighter
- rendered for each code tag the SyntaxHighlighter component
Quale theme è piu figo da usare

feat: add highlight code with react-syntax-highlighter

---

src/feature/projects/components/HomeSection.tsx
src/feature/projects/components/ProjectSection.tsx
src/feature/projects/components/index.ts
src/feature/projects/types/index.ts
src/pages/index.tsx
theme.js

- Creato componente per gestire la lista di 3 progetti
- Fix assurdo nel tema che dal nulla ha smesso di funzionare

feat: create ProjectSection Component

---

src/feature/projects/components/LinkSection.tsx

Aggiunto Link al chip della categoria del progetto

fix: add SeoLink to category chip

---

src/feature/projects/components/ArticleHero.tsx
src/feature/projects/components/LatestProject.tsx
src/feature/projects/components/index.ts
src/template/ProjectsHome.tsx

- modificato la query
- creato il componente LatestProject 
Siccome ho modificato la query credo che sia da mergiare prima questa, poi sistemo l'altra del body #58

feat: create latest project section

---

src/template/ProjectsHome.tsx

- Renderizzato i progetti utilizzando ProjectSection

feat: render dei progetti pagina /progetti/

---

gatsby-node.js
query.js
src/components/ui/navigation/layout.tsx
src/feature/navigation/components/Paginatior.tsx
src/template/ProjectArticle.tsx
src/template/ProjectsCategory.tsx
src/utils/helpers.ts

- Paginazione SSR
- Render Section delle categorie
- Paginator component

Render template categorie progetti

---

gatsby-config.js
src/components/SEO/components/LinkHandler.tsx
src/template/Category.tsx
src/template/ProjectsCategory.tsx
src/template/ProjectsHome.tsx
src/template/SingleCoursePage.tsx

- Creato Schema/Meta/Alternate Link in Projects Home & Projects Category
- Gestita la paginazione lato SEO
- Rimossi duplicate e paginazione dalla sitemap generation (need to be tested on staging)

feat: Implements Seo in Projects Home & Projects Category

---

src/feature/projects/components/ArticleBody.tsx
src/feature/projects/components/LatestProject.tsx
src/feature/projects/components/ProjectCard.ts

Aggiunto la proprietà `transform: translateZ(0)` alle immagini della sezione dei progetti

fix safari images

---

src/feature/projects/components/ProjectBanner.tsx

- Aggiunto un box che contiene il bottone da fixare

fix banner button width

---

src/feature/projects/components/ProjectBanner.tsx

Sistemato asterischi e line height

fix title nel banner svolazzante

---

gatsby-node.js
query.js
src/feature/projects/components/HomeSection.tsx
src/feature/projects/components/LatestProject.tsx
src/feature/projects/components/LinkSection.tsx
src/feature/projects/components/ProjectBanner.tsx
src/template/ProjectArticle.tsx
src/template/ProjectsHome.tsx

- Last project show first one in related section
- Fix broken home page paths
- Fix Projects Home link & label hover

Handle projects links

---

gatsby-config.js
package.json
yarn.lock

- Bestemmiato la madonna con la pull request di prima

chore: ritento con sto cazzo di plugin

---

src/api/calendar/book-appointment.ts
src/server/constants/index.ts
src/server/utils/api.ts
src/server/utils/index.ts

book-appointment function includes a new optional body params to send an email after the consulenza is fixed.

feat: add function to send mail after booking an apointment

---

src/hook/useSteps.ts

Creato hook per gestire la progressione degli step

feat: create useStep hooks helpers

---

package.json
src/components/modal/ModalOverlay.tsx
src/components/modal/index.ts
yarn.lock

Creato Overlay per i modali, al quale si può passare sia il colore che la funzione per la chiusura del modale tramite l'onClick sull'overlay

feat: create modal overlay

---

src/components/modal/Modal.tsx
src/components/modal/ModalBody.tsx
src/components/modal/ModalElipse.ts
src/components/modal/index.ts
src/feature/consulenze/components/ReservationModal.tsx

- Remove useless code.
- Rimosso padding dall'intero `<ModalBody>` usiamo un semplice Container di MUI per gestire gli spazi
- Creata ModalElipse per cose belline con background viola

feat: aggiunto modal Elipse component

---

src/components/SEO/components/WebPageSchema.tsx
src/components/SEO/hooks/useOrganizationSchema.ts
src/components/SEO/hooks/useWebPageSchema.ts
src/components/SEO/types/index.ts
src/components/shared/Insegnante.tsx
src/pages/about.tsx
src/template/Consulenze.tsx

- Add to WebPageSchema field type to specify more accurate type of metaData
- Used in all pages that needs this specification
- Expanded OrganizationSchema

feat: add seo & metaData contactPage

---

src/feature/footer/footerdata.ts
src/feature/navigation/hooks/useNavigationLink.ts

- Messo link per le consulenze nella navbar, nella sidebar e nel footer

feat: modificato navbar sidebar e footer links

---

gatsby-node.js
src/feature/projects/components/LinkSection.tsx
src/pages/join-us.tsx

- Add h1 heading to join us page 
- Add `nofollow` to external project link
- make all project slug to lowercase

fix: remove all broken seo & missing headings

---

src/components/modal/ModalTab.tsx
src/feature/consulenze/components/ProviderModal.tsx

Provider modal

---

src/feature/consulenze/components/InfoModal.tsx

fix mobile view

---

GlobalProvider.tsx
gatsby-browser.js
gatsby-browser.ts
gatsby-config.ts
gatsby-node.ts
gatsby-ssr.ts
query.ts
theme.ts
tsconfig.json
useServeStaticFonts.tsx

## Done
- Core files convertiti in typescript Closes #226 
- theme.js convertito in typescript ( filippinata dell'anno )

feat: all core gastby files converted in typescript

---

src/api/calendar/book-appointment.ts
src/api/calendar/get-all-calendars.ts
src/api/calendar/get-appointment-by-mail.ts
src/components/modal/ModalHeader.ts
src/components/modal/ModalTab.tsx
src/feature/consulenze/components/DatepickerModal.tsx
src/feature/consulenze/components/InfoModal.tsx
src/feature/consulenze/components/ProviderModal.tsx
src/feature/consulenze/components/WelcomeModal.tsx
src/services/calendar/index.ts

Improve generale della sezione che prenota le date.
- Ora la chiamata per tutti i calendari ti ritorna anche `appointmentStatus= 'booked' | 'free'`.
- Le Date ora sono oridinate per data d'inizio e non per data di update Closes #230 
- Gestito Allineamento e layout se le colonne diventano 4
- Fixati warning di utilizzo scorretto di variabili `hasBorder`, `isMobile`, `isGmail` (componenti accettano solo argomenti tutti minuscoli`
- Disabilitato il bottone se utente non sceglie nulla

Improve get calendar list fn

---

gatsby-config.js
package.json
yarn.lock

- Cambiato configurazione di Gtag e analitycs.
- Prego il signore che funzioni ancora tutto dio ladro.
- Porco dio, porco dio

Sono il capo dei coglioni

---

src/components/banner/ComunityBanner.tsx
src/components/banner/CourseBanner.tsx

- Fixato imports nella folder components/banner

fix: material ui imports in banner folder

---

src/components/banner/ComunityBanner.tsx

fix: changed discord invite link

---

src/components/SEO/components/CourseSchema.tsx
src/components/SEO/hooks/useCourseSchema.ts
src/components/SEO/types/index.ts
src/components/shared/Insegnante.tsx
src/feature/courses/components/CourseAlignment.ts
src/feature/projects/components/Projects.tsx
src/template/Category.tsx
src/template/courses/FreeCourse.tsx
src/template/courses/UdemyCourseTemplate.tsx

- Add new `Review` type inside `Course Schema`
- Fix `key` alert in console
- Fix `errore a cazzo di material UI su props full`
- Pass to `CourseSchema` all Review that we save on GraphQL Layer

Hpv4 lear 29 migliorare dati strutturati per le recensioni

---

src/components/modal/ErrorModal.tsx
src/components/modal/ModalTab.tsx
src/feature/consulenze/components/CardsSection.tsx
src/feature/consulenze/components/Hero.tsx
src/feature/consulenze/components/SuccessModal.tsx
src/feature/consulenze/components/WelcomeModal.tsx
src/feature/footer/Footer.tsx
src/feature/navigation/components/Navbar.tsx

Tolto tracedSVG da tutti i placeholders

fix: replaced placeholders in all gatsby images

---

src/components/SEO/hooks/useCourseSchema.ts
src/components/banner/CourseBanner.tsx

- Tolto la cazzata del coupon esaurito che disabilita il bottone
- Fixato errore nei dati strutturati per review con valore = 0

Hotfix review snippets when 0

---

src/constants/index.ts
src/feature/courses/components/NextCourseBanner.tsx
src/feature/courses/context/CourseBanner.tsx
src/global.d.ts
src/template/ProjectArticle.tsx
src/template/courses/FreeCourse.tsx
src/utils/tracking.ts

- Passata una nuova props al context dei banner che accetta una callback perché i banner sono riutilizzati in diversi punti
- Gestito il type dell'oggetto `dataLayer`

Hpv4 lear 136 creare tracking su gtm di next course banner

---

src/components/banner/BannerCard.tsx

Mi ero missato di invocare la closure per il tracciamento nel community banner

call fucntion to dispatch discord & yt event

---

src/feature/guide/GuideInfo.tsx
src/feature/guide/VideoSection.tsx
src/template/Guide.tsx

- Aggiunto box degli studenti quando il corso è a pagamento
- Invocato il tracciamamento anche quando si clicca sull'immagine

add students 4 payable course & track when call handle navigate

---

tsconfig.json

Tolto l'errore del cazzo che faceva piangere react

fix: errore nell import di react
